### ISSUE TITLE
Add a trim command

### ISSUE THREAD

**Issue by othorotka** [orf/hq#1]
hey!
tried to use the tool to scrape a table out of a page :/
I did `hq '#<ID_OF_TABLE> > tbody` and the output was not valid json :(
I needed to run a pre-trim and post-trim on the data

if you can add a `trim` module that will remove pre and post whitespaces that would be great (I could ask the `jq` team the same but starting here)

**Comment by orf** [comment]
Hey, I’m confused. Can you be a bit more clear when you create issues?

you’re saying that the output was not valid JSON. What output? If it’s not valid JSON then that’s an issue. Can you show your output?

I like the idea of a trim filter. Do you mean like `.foo | @trim` or some such

**Comment by othorotka** [comment]
yeah, give me a sec to open from a different account (my bad)
