### ISSUE TITLE
trim command :/

### ISSUE THREAD

**Issue by georgettica** [orf/hq#2]
hey!
tried to use the tool to scrape a table out of a page :/
I did hq '#<ID_OF_TABLE> > tbody and the output was not valid json :(
I needed to run a pre-trim and post-trim on the data

if you can add a trim module that will remove pre and post whitespaces that would be great (I could ask the jq team the same but starting here)

**Comment by orf** [comment]
Hey @georgettica - I'm really not sure what the issue could be here. I'm willing to add a trim command, but the output of the tool should always be valid JSON 🤔

**Comment by zexa** [comment]
This would be actually useful as I do sometimes get untrimmed html:

```
cat example.html | hq '{title: .left-block > h1:nth-child(1)}'                
{"title":"\n                            Lenovo Thinkpad X1 Carbon                        "}
```

**Comment by orf** [comment]
Ok, this makes sense. I'm thinking - when would you ever want it to _not_ be trimmed? Shouldn't we just trim all output?

prefix/suffix whitespace isn't significant in html anyway right?
