### ISSUE TITLE
Arrays always have only one item

### ISSUE THREAD

**Issue by vsviridov** [orf/hq#38]
Hello, I'm trying to parse the release page for Gitea (https://dl.gitea.com/gitea/) and no matter what it always returns an array with a single item.

I'm trying the simplest query possible, e.g. `curl https://dl.gitea.com/gitea | hq '{a: [a]}'` and I get back `{"a":["Gitea"]}`, whereas I would expect all links in the output...

**Comment by orf** [comment]
Hey, by default the elements text is returned. If you want a specific attribute you need to add `a | @(href)`. This is explained in the readme, but I can make it more prominent.

can you let me know if this works?

**Comment by vsviridov** [comment]
Hey, thanks for the quick reply...

I've tried it with `[a|@(href)]` and it still only gives me one...

<img width="453" alt="image" src="https://user-images.githubusercontent.com/221684/226506574-210ae0e6-8cbb-418e-af28-83f75df9d55b.png">

**Comment by orf** [comment]
Ah, this might be an unexpected limitation. I’m currently travelling without my laptop so I’m unable to help much for a week or so, but can you try:

`hq '{a: [{url: @(href)}]}'`

**Comment by vsviridov** [comment]
That worked, thank you.
